version: '3.8'

services:

  product-service:

    build: .

    container_name: product-service

    environment:
        DB_URL: ${DB_URL}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        JWT_SECRET: ${JWT_SECRET}

    ports:
      - "8081:8081"